
compile: 
	gcc -o ccalc.o ccalc.c

debug:
	gcc -o ccalc.out ccalc.c
	gdb ccalc.out

run: 
	./ccalc.o

it do something:
	clear
	gcc -o ccalc.o ccalc.c
	./ccalc.o

edit:
	vim ccalc.c

clear:  
	rm *.o
	rm *.out
