
compile: 
	gcc -o bitcalc.o bitcalc.c

debug:
	gcc -o bitcalc.out bitcalc.c
	gdb bitcalc.out

run: 
	./bitcalc.o

it do something:
	clear
	gcc -o bitcalc.o bitcalc.c
	./bitcalc.o

edit:
	vim bitcalc.c

clear:  
	rm *.o
	rm *.out
